### ISSUE TITLE
No dark theme for first column of csv preview

### ISSUE THREAD

**Issue by NoobiCodi** [poychang/github-dark-theme#106]
Hello,
there is no dark theme for first column and the first line of csv file preview.
voila
<img width="1050" alt="Screenshot 2019-12-30 at 13 58 57" src="https://user-images.githubusercontent.com/35873522/71582969-bbe26600-2b0c-11ea-9f1e-0c22263bb371.png">

**Comment by jiaming0708** [comment]
do you give us the link?

**Comment by IamCathal** [comment]
I think github is doing something weird behind the scenes to cause that. Heres a link to an example of a csv file on github: https://github.com/datapackage-examples/sample-csv/blob/master/sample.csv

Targeting the top row element (`<tr id="LC1" class="js-file-line">`) with `js-file-line` and giving the style `background-color: green` doesn't seem to work.
