### ISSUE TITLE
no dark mode under 'pull-request -> filter'

### ISSUE THREAD

**Issue by AmitShe** [poychang/github-dark-theme#109]
no dark mode under 'pull-request -> filter', it's all regular.

![image](https://user-images.githubusercontent.com/38208025/71661807-0c99cf00-2d58-11ea-8857-a3227c8c3a77.png)

**Comment by MagnusHvidsten** [comment]
Not an issue for me 
![image](https://user-images.githubusercontent.com/9809262/72651080-27af3600-3937-11ea-94c1-2ed684db4c8c.png)

**Comment by AmitShe** [comment]
weird, now it works for me...
I have no idea why...
