### ISSUE TITLE
Dark mode on 2FA page disables QR code scanning

### ISSUE THREAD

**Issue by vnagarnaik** [poychang/github-dark-theme#113]
I recently went through reconfiguring the 2FA tokens and with this extension enabled, the phone camera could not read the QR code which contains the 2FA secret and account details.

When I disabled the extension and reloaded the page, the phone was able to read the QR code correctly.

Although the QR code "looked" correct, it wasn't valid. May be dark mode caused the image to be inverted so that the scanning failed?

I think one way to solve it is to disable dark mode on 2FA page which is always at a fixed URL.

**Comment by poychang** [comment]
![image](https://user-images.githubusercontent.com/4879879/73413555-fe36d700-4346-11ea-954e-a9e95d601501.png)

I think it will work with this fix.

**Comment by jiaming0708** [comment]
released v1.0.39
