### ISSUE TITLE
GitHub news are unreadable

### ISSUE THREAD

**Issue by bershanskiy** [poychang/github-dark-theme#124]
If extension is disabled:
![Untitled](https://user-images.githubusercontent.com/45960703/73684947-344fc000-4693-11ea-9130-7b2fbf5d5a9d.png)

When extension is enabled:
![GitHubpng](https://user-images.githubusercontent.com/45960703/73684821-f2267e80-4692-11ea-96a9-feb74715e75f.png)

**Comment by poychang** [comment]
fixed with v1.0.44
