### ISSUE TITLE
White bar appeared today

### ISSUE THREAD

**Issue by valeriyo** [poychang/github-dark-theme#127]
Started seeing this white bar today:

<img width="1086" alt="Github_dark_theme" src="https://user-images.githubusercontent.com/7052801/74074088-89584280-49c1-11ea-8c8f-0099bea76aee.png">

**Comment by hacker0limbo** [comment]
I encountered same problem here, and i found white bar appears for `Issues`, `Pull request`, `Projects`, `Wiki`, `Security` and `Insights` these tabs. Only `Code`, `Actions` and `Settings` appears normally.

**Comment by wangkanai** [comment]
Me too, GitHub is looks like that is updating the design.

## Issue now;
- [ ] [Code](https://github.com/wangkanai/Detection)
- [ ] [Issue](https://github.com/wangkanai/Detection/issues)
- [ ] [Pill Request](https://github.com/wangkanai/Detection/pulls)
- [ ] [Action](https://github.com/wangkanai/Detection/actions)
- [ ] [Projects](https://github.com/wangkanai/Detection/projects)
- [ ] [Wki](https://github.com/wangkanai/Detection/wiki)
- [ ] [Security](https://github.com/wangkanai/Detection/network/alerts)
- [ ] [Insights](https://github.com/wangkanai/Detection/pulse)

## Not yet

- [Settings](https://github.com/wangkanai/Detection/settings)

![image](https://user-images.githubusercontent.com/10666633/74094619-d26ddb00-4b16-11ea-808e-15725b87410a.png)

**Comment by wangkanai** [comment]
pagehead.scss - line 74
```css
@media (min-width: 768px)
.page-responsive .pagehead {
    background-color: #fafbfc!important;
}
```

**Comment by poychang** [comment]
Thanks for this report. This fix already merged. Next version will be better.

**Comment by wangkanai** [comment]
Thank you, Do you have a release date?

**Comment by poychang** [comment]
@wangkanai v1.0.43 already published in Firefox, but chrome version still under review. The release date depend on Chrome Web Store.

**Comment by syedmohsinbukhari** [comment]
I am having the same issue

**Comment by wangkanai** [comment]
@poychang This no luck on the google extension store review yet?

**Comment by poychang** [comment]
@wangkanai unfortunately yes... I send a complaint email to Chrome Web Store. They were publish fast before, but now is like take forever. Unlike Firefox Add-on, they only spend less an hour. 😥

**Comment by ImLucasBrown** [comment]
I lived with this for a few days, glad a fix is coming. :)

**Comment by poychang** [comment]
Finally pass! enjoy 1.0.43 😃

**Comment by syedmohsinbukhari** [comment]
a great service to GitHub beings
