### ISSUE TITLE
Authentication page to Bintray has incorrect coloring - maybe all OAuth?

### ISSUE THREAD

**Issue by julianparismorgan** [poychang/github-dark-theme#135]
If you authenticate with Bintray, the OAuth page has hard to read coloring. Maybe all OAuth pages have this issue?

**Comment by Elandig** [comment]
Preventing myself from duplicating this issue. I can confirm that all OAuth pages don't seem to look right.

![image](https://user-images.githubusercontent.com/15586732/82576059-fb7c1e00-9b91-11ea-9d92-55621f8db53d.png)

**Comment by 10OsamaAhmed92** [comment]
It's Darkness

**Comment by IamCathal** [comment]
Working on a fix for this at the moment
