### ISSUE TITLE
Black graph axis in insights

### ISSUE THREAD

**Issue by Peter92** [poychang/github-dark-theme#136]
Some of the graph axis have a very suitable light grey colour, but a few of them have black text which makes it hard to read.

Also below you can see on the git clones section, the text there is almost invisible.

![image](https://user-images.githubusercontent.com/10235666/74934976-4776c580-53df-11ea-8030-80ffe4ab046c.png)

![image](https://user-images.githubusercontent.com/10235666/74934925-2f06ab00-53df-11ea-86c0-5596bd5582c9.png)

**Comment by 3runoDesign** [comment]
Fix in https://github.com/poychang/github-dark-theme/pull/189.

**Comment by 3runoDesign** [comment]
![image](https://user-images.githubusercontent.com/1563041/85487764-93ab5f80-b5a3-11ea-8878-c588e7671a46.png)
![image](https://user-images.githubusercontent.com/1563041/85487789-9dcd5e00-b5a3-11ea-9e65-b5a2b2160cd2.png)

**Comment by Peter92** [comment]
Nice one, working fine
