### ISSUE TITLE
GitHub sponsors notice shows up with white background

### ISSUE THREAD

**Issue by Jasius** [poychang/github-dark-theme#140]
Hey,

I've installed this extension today and noticed one minor issue within the homepage of GitHub
![image](https://user-images.githubusercontent.com/11031051/75915576-7b320080-5e5f-11ea-9cce-8473bdec7e93.png)

Sponsors notice appears with white background unlike everything else, I'd submit a PR for this minor issue myself but I am not sure where I should put the styles and such that would fit your project.

If you'd give me some pointers I would submit a PR with the fix.

**Comment by poychang** [comment]
Put it into `/src/theme/misc.scss` will be fine. Looking forward your PR 😀

**Comment by Jasius** [comment]
> Put it into `/src/theme/misc.scss` will be fine. Looking forward your PR 😀

Cheers.
