### ISSUE TITLE
No Dark Theme at Find File field

### ISSUE THREAD

**Issue by thiagolunardi** [poychang/github-dark-theme#143]
![image](https://user-images.githubusercontent.com/5428523/76204030-eaa94680-61f7-11ea-828f-cb9144ce69a0.png)

**Comment by poychang** [comment]
![image](https://user-images.githubusercontent.com/4879879/77127186-8f444780-6a86-11ea-9fa8-2fc7bb68dad2.png)

It will be dark on next. Thanks for your report.
