### ISSUE TITLE
Config doesn't affect the page rendering anymore (instantly)

### ISSUE THREAD

**Issue by valeriyo** [poychang/github-dark-theme#144]
I used to be able to change plugin config and refresh the page to quickly switch themes at github.com. With Chrome version 80.0.3987.132 (Official Build) (64-bit) that doesn't work anymore - I change config, refresh the page -- nothing changes. I restart Chrome -- still no change. After a while, it does change, not sure what causes it though.

**Comment by poychang** [comment]
related #145
