### ISSUE TITLE
Theme applying on Github Enterprise domain and disappears from menu

### ISSUE THREAD

**Issue by vc1492a** [poychang/github-dark-theme#145]
After adding `github.jpl.nasa.gov` to the list of domains (see [image](https://imgur.com/PeuwNQR)), the domain is added to the list of domains. However, on subsequent selection of the extension icon or a refresh of the page, the theme does not apply and the domain is no longer visible in the menu.

**Comment by poychang** [comment]
this issue will be fix by next version 1.0.46
Thanks for your reports.
