### ISSUE TITLE
Not working at all

### ISSUE THREAD

**Issue by davidgilbertson** [poychang/github-dark-theme#147]
I must be missing something obvious. I installed the Chrome extension and it doesn't work at all.

When I first opened the extension window it didn't have any domains. I hit reset and now it has this:
![image](https://user-images.githubusercontent.com/4443482/76945727-0da1cc00-6957-11ea-8c7b-1f6a61529724.png)

If I paste in a domain to that window and hit add, it just disappears and all github pages stay light.

Am I supposed to be doing something else to turn on the dark mode?

Chrome version: 80.0.3987.132
Windows.

**Comment by poychang** [comment]
Please update to latest version.  You face a bug that pervious version has.

**Comment by xy137** [comment]
just downloaded from the chrome extension store and have the same issue.

**Comment by poychang** [comment]
sorry, you are right. it has somewhere goes wrong. I clean test on my machine with latest code, it works fine. I just published v1.0.47 to chrome store, and wait for review now. Please give me feedback, if you face the same issues with v1.0.47
@davidgilbertson @xy137 Thank for you report.

**Comment by poychang** [comment]
oh... I find out where cause this problem and I fix it. It will work fine with v1.0.47.

**Comment by netpoe** [comment]
> oh... I find out where cause this problem and I fix it. It will work fine with v1.0.47.

Not seeing version 1.0.47 in Chrome Extensions.

**Comment by poychang** [comment]
@netpoe because it's under review stage...
