### ISSUE TITLE
Feature Request: Add a blacklist

### ISSUE THREAD

**Issue by GuyKh** [poychang/github-dark-theme#149]
Hey.

I'm using this great extension in my Enterprise Github.
so I added `git.myOrg.com` to the list and it works great.

The only problem - Github Pages (`git.myOrg.com/pages`) is also changes it's colors to dark.

I'd really like to see a BlackList - e.g. Don't modify this prefix

**Comment by poychang** [comment]
![image](https://user-images.githubusercontent.com/4879879/78862277-9220cf80-7a69-11ea-8a45-6f925729436c.png)
This feat is publish 😀
