### ISSUE TITLE
[BUG] no dark theme in  Insights/network

### ISSUE THREAD

**Issue by DiogoVieiraFerreira** [poychang/github-dark-theme#151]
On the network graph page in Insights menu, the body of graph is white.
![image](https://user-images.githubusercontent.com/47444284/78187738-42417780-746f-11ea-8758-3e38f0e14322.png)

**Comment by amirtezgalinew** [comment]
https://githu@DiogoVieiraFerreira DiogoVieiraFerreira changed the title no dark theme in Insights/network [BUG] no dark theme in Insights/network on Apr 2
@poychang poychang added the help wanted label on Apr 24b.cohttps://github.com/poychangm/DiogoVieiraFerreira

**Comment by RedSparr0w** [comment]
This seems to be resolved?
![image](https://user-images.githubusercontent.com/7288322/97099671-63f69a80-16f0-11eb-8e15-879835723beb.png)

**Comment by DiogoVieiraFerreira** [comment]
> This seems to be resolved?
> ![image](https://user-images.githubusercontent.com/7288322/97099671-63f69a80-16f0-11eb-8e15-879835723beb.png)
> 

I think it's very nice and resolved if we've the same result of the picture

**Comment by poychang** [comment]
This one is resolved 😀
