### ISSUE TITLE
Styles on organizations page seem to be broken

### ISSUE THREAD

**Issue by huyenltnguyen** [poychang/github-dark-theme#161]
Organizations page: https://github.com/organizations/plan

Screenshot

<img width="1061" alt="Screen Shot 2020-04-23 at 2 34 54 AM" src="https://user-images.githubusercontent.com/25715018/80025553-0b5cff80-850b-11ea-831f-f42749420dfb.png">

**Comment by poychang** [comment]
You can exclude this page 😅
![image](https://user-images.githubusercontent.com/4879879/80178543-0b571f80-8631-11ea-9a5e-b2ac60110de0.png)

**Comment by huyenltnguyen** [comment]
Oh cool! I thought we supported this page, since the page looks so nice in dark mode, except that part lol
