### ISSUE TITLE
Fix organization's "Invite your teammates" input bar

### ISSUE THREAD

**Issue by Elandig** [poychang/github-dark-theme#163]
### Screenshot:
![image](https://user-images.githubusercontent.com/15586732/80159509-d5378280-85d3-11ea-81bf-228fbdc2a51e.png)

**Comment by poychang** [comment]
It will be fix in next version.
![image](https://user-images.githubusercontent.com/4879879/80178007-dbf3e300-862f-11ea-90d8-641b59e05fc5.png)
