### ISSUE TITLE
Dark theme for release selectors

### ISSUE THREAD

**Issue by esatterwhite** [poychang/github-dark-theme#168]
on the releases page, you can select a list of release to compare against a single release. The drop down isn't styled.
![2020-04-29 17 13 42 github com 5e3a96fa90c9](https://user-images.githubusercontent.com/148561/80652203-16e58480-8a3d-11ea-8e6e-d18a82b8197c.png)

**Comment by poychang** [comment]
I can overwrite the background color. But I think this should be a mistake form them. According their CSS class pattern, they should use `select-menu-item` not `SelectMenu-item` .
![image](https://user-images.githubusercontent.com/4879879/80815212-c9fddb80-8bff-11ea-9c4e-efcfd4854e60.png)

When I change that class into `select-menu-item`, only first item form list. The background color perform correctly like below.
![image](https://user-images.githubusercontent.com/4879879/80815289-f3b70280-8bff-11ea-8b7d-85f8027e118b.png)

**Comment by IamCathal** [comment]
I don't know when but this issue can be closed as it is no longer a problem on the latest version of github-dark-theme

![](https://i.imgur.com/rfbFVlS.png)

**Comment by elibroftw** [comment]
![image](https://user-images.githubusercontent.com/21298211/90459982-e2bbcf80-e0d0-11ea-8d46-a258e6bb427c.png)
But this dropdown when you create and edit a release is an issue still for 1+ month.

**Comment by IamCathal** [comment]
Ah ok sorry about that. I was looking at the wrong thing. I'll fix it up now

**Comment by elibroftw** [comment]
how many times do you have to contribute to the project to get that Contributor badge? I see you have 4 commits but I have 1.

**Comment by IamCathal** [comment]
I'm not sure actually. How about we find out then. Do you want to make this PR then? All that needs to be done is to add
```css
.autocomplete-item {
    color: $text-color !important;
}
```
to the bottom of `src/theme/misc.scss`. I can do it easily enough but if you're not sure how to do it it'd be better to have you go through it again so you can learn it :)

**Comment by elibroftw** [comment]
No, I'm good, I have my own projects to maintain, my fork is also outdated and I don't want to do that merge thing
