### ISSUE TITLE
Incorrect font size for Markdown text between backticks in headers

### ISSUE THREAD

**Issue by rdeago** [poychang/github-dark-theme#171]
The following piece of Markdown

```Markdown
## How to use `MyClass`
```

will render `MyClass` in 12px font size, despite the fact that it is in a header.

Example: [EmbedIO Cookbook](https://github.com/unosquare/embedio/wiki/Cookbook#form-values-applicationx-www-form-urlencoded)

Removing `github.com` from the domain list (or deactivating GitHub DarkTheme) fixes the font size.

This seems to be caused by the following CSS code inserted in the page:

```CSS
code, pre, tt {
    font-size: 12px !important;
}
```

**Comment by poychang** [comment]
Thanks for your report. It will be fix with next version.
