### ISSUE TITLE
Permissions for all sites

### ISSUE THREAD

**Issue by cyrus-za** [poychang/github-dark-theme#174]
I got an update on my firefox plugin stating it needs new permissions. I checked and saw that it requires access to all sites.

I naturally came here to see if there's any new commits that might be related to it and found this: https://github.com/poychang/github-dark-theme/commit/57be3abf01f1f1969e18e6ecee3167f5a3342628

This means that the majority of us, who do not have enterprise accounts, are now forced to allow all domains just so that it works for enterprise github accounts. 

Let's rather make that opt-in please

**Comment by pckilgore** [comment]
For anyone else similarly concerned, I suggest disabling updates in the interrim: 
![image](https://user-images.githubusercontent.com/2559043/81116380-de392580-8eea-11ea-9ad8-5e7b7e0d3465.png)

**Comment by poychang** [comment]
Thanks report. Please discuss here #123.
