### ISSUE TITLE
Clicking a link on Github to external website applies styling to that site

### ISSUE THREAD

**Issue by antonbramsen** [poychang/github-dark-theme#175]
I clicked a link in the readme of React Router and saw that the styling was off. Refreshing a site fixes the issue. 

<img width="1183" alt="Screenshot 2020-05-06 at 20 38 45" src="https://user-images.githubusercontent.com/7079302/81215702-00f63780-8fda-11ea-8a53-d533301f0917.png">

How it should look:
<img width="1081" alt="Screenshot 2020-05-06 at 20 41 52" src="https://user-images.githubusercontent.com/7079302/81215753-166b6180-8fda-11ea-9120-08fc5edd9349.png">

I'm using version `1.0.53` of the plugin on Firefox on Mac OS

**Comment by FrancYescO** [comment]
+1

**Comment by WPMGPRoSToTeMa** [comment]
Also happens when going backward in the tab history (e.g. opening github link on reddit and then going back to reddit).

**Comment by lopis** [comment]
This is a bit annoying. Refreshing the page reverts the style to normal. I don't use this extension on any other websites than github.com, so I wish it would be possible to disable the extra permission

**Comment by tojin12341za** [comment]
+1

**Comment by WPMGPRoSToTeMa** [comment]
I've recently updated the extension from a pretty old version and looks like this bug was fixed. As I can see this was done in b5de468. So I think the issue can be closed.

**Comment by WPMGPRoSToTeMa** [comment]
Unfortunately I'm still having the issue when going back from a github page.
