### ISSUE TITLE
Available for custom domain

### ISSUE THREAD

**Issue by raphaelauv** [poychang/github-dark-theme#176]
Hey , thanks for your work !

We have a pro version of github , http;//github.mycompagny.com

Would be nice to be able to activate the plugin on custom domains

**Comment by poychang** [comment]
Yes you can add custom domains. Use setting menu like below.
![image](https://user-images.githubusercontent.com/4879879/82432383-91e10e80-9ac2-11ea-9c0b-f6fe735f1b6e.png)

**Comment by raphaelauv** [comment]
I'm sorry for the stupid question, thank you !!

**Comment by poychang** [comment]
Not a problem. Thanks your comment. 😃
