### ISSUE TITLE
Gist banner is not dark

### ISSUE THREAD

**Issue by CorentinDy** [poychang/github-dark-theme#178]
Hi,
I've just discover your extension and it is awesome ! 

On Gist I saw the gist-banner still whitish, I was wondering if you can make it black, or if it's not fixable.
![image](https://user-images.githubusercontent.com/6079068/81666313-2b188100-9442-11ea-833d-fb67eec24f1e.png)

Thanks for you project ! It saved my eyes

**Comment by poychang** [comment]
You can sign in and it will be gone 😀
Thanks your comment.
