### ISSUE TITLE
1.0.53 is broken no problem with 1.0.52

### ISSUE THREAD

**Issue by Neustradamus** [poychang/github-dark-theme#186]
1.0.53 is broken no problem with 1.0.52

**Comment by poychang** [comment]
please share more information. close this issue. reopen this issue with more info.

**Comment by Neustradamus** [comment]
@poychang: Please test with Firefox 56.0.2:
- http://productdeliveryorigin-default.prod.mozaws.net/pub/firefox/releases/56.0.2/

**Comment by poychang** [comment]
![image](https://user-images.githubusercontent.com/4879879/82510498-4455b780-9b3d-11ea-9109-1ca5dc1da39c.png)
@Neustradamus The theme seem right. But the custom domain is not working. Is custom domain your problem?

**Comment by Neustradamus** [comment]
@poychang: I have the bug with normal github.com...
Update of 1.0.52 to 1.0.53, GitHub has now "white" background and when I click on the button, I have a menu and no possibility to enable "black" background...
I downgrade to 1.0.52, no button and "black" background again :)
