### ISSUE TITLE
Missing dark theme on sidebar of Security tab

### ISSUE THREAD

**Issue by julienbenisty** [poychang/github-dark-theme#190]
The dark theme is not applied to the sidebar of the Security tab as seen on the screenshot.
I'm on:
- MacOS 10.15.4
- Chrome 83.0.4103.61 (Official Build) (64-bit)
- GitHub Dark Theme 1.0.53

![GitHub-dark-theme-security-tab](https://user-images.githubusercontent.com/381525/83339027-c198cf00-a297-11ea-880e-5c55aa5fe735.jpg)

**Comment by poychang** [comment]
This issue is fixed in next version. Thanks report.
