### ISSUE TITLE
'Add Code of Conduct' Page not styled

### ISSUE THREAD

**Issue by michaeldera** [poychang/github-dark-theme#195]
The Add Code of Conduct section under community is not completely styled.  

![image](https://user-images.githubusercontent.com/12817839/83741805-f53d7580-a658-11ea-8752-2c257f56e7dd.png)

## To Reproduce

1. Navigate to 'Insights' under the Insights tab on a project.
2. Click on the 'Community' section in the sidebar on the left.
3. Click on 'Code of Conduct'.

## Environent.

- Browser: Microsoft Edge (Chromium) Version 83.0.478.44
- OS: Windows 10

**Comment by michaeldera** [comment]
License page is also similar 
![image](https://user-images.githubusercontent.com/12817839/83742971-5a459b00-a65a-11ea-9d9d-324689e5c22d.png)

**Comment by poychang** [comment]
This issue is fixed in next version. Thanks report.
