### ISSUE TITLE
auto-theme switch keeps resetting

### ISSUE THREAD

**Issue by abc876** [poychang/github-dark-theme#199]
Switch theme automatically based on system preferred scheme <-this switch keeps resetting itself with every chrome restart.

**Comment by N0tMyFaultOG** [comment]
Same, I can't put on my sun glasses fast enough before it switches back.

**Comment by jho2301** [comment]
Same too

**Comment by poychang** [comment]
I remove that part of code to accelerate wearing sunglasses performance. (published in v1.1.1)

**Comment by BrunuNC** [comment]
> 
> 
> Switch theme automatically based on system preferred scheme <-this switch keeps resetting itself with every chrome restart.

At all browsers

**Comment by poychang** [comment]
The switch feature is removed. This problem should be gone.
