### ISSUE TITLE
Text is not clearly visible in Search Bar while typing.

### ISSUE THREAD

**Issue by DTan13** [poychang/github-dark-theme#202]
### While typing in Search Bar, text is not perfectly visible. 

![Search Text Not Selected](https://user-images.githubusercontent.com/48372719/83974985-b33d5980-a90e-11ea-8afe-190eb476d2fd.jpg)

### Text is visible after selecting it.

![Search Text Selected](https://user-images.githubusercontent.com/48372719/83974986-b59fb380-a90e-11ea-8dce-44777c219286.jpg)

**Comment by MPV** [comment]
Looks like it's being fixed by #201.

**Comment by DTan13** [comment]
Yes!!
Thank You!!
