### ISSUE TITLE
Button shading for selected Check

### ISSUE THREAD

**Issue by guidezpl** [poychang/github-dark-theme#204]
I think this is causing it 
```
.position-absolute {
    background: linear-gradient(to top, rgb(27, 29, 35), rgba(27, 29, 35, 0)) !important;
}
```

<img width="207" alt="Screenshot 2020-06-09 at 12 04 18" src="https://user-images.githubusercontent.com/6655696/84135024-bbe67a80-aa49-11ea-9911-40f53bac8a41.png">

**Comment by poychang** [comment]
Thanks!! You are right about it.
