### ISSUE TITLE
Active search text color

### ISSUE THREAD

**Issue by 3runoDesign** [poychang/github-dark-theme#205]
The color of the text in the search field when active does not contrast with the background.

![image](https://user-images.githubusercontent.com/1563041/84384053-c6c51a80-abc3-11ea-9c59-30c96e295a33.png)

**Comment by MPV** [comment]
Looks like it's being fixed by #201.

**Comment by 3runoDesign** [comment]
> Looks like it's being fixed by #201.

Nice... i will close these issue!
