### ISSUE TITLE
Can`t read black text in search bar

### ISSUE THREAD

**Issue by erth5** [poychang/github-dark-theme#207]
The text in th search bar is not readable, because it is black like th search bar

so don't change the search bar color or set it in white

![bdgfs](https://user-images.githubusercontent.com/9325448/84435649-7933c680-ac32-11ea-85db-026cd5f8a7ab.png)

**Comment by MPV** [comment]
Looks like it's being fixed by #201.

**Comment by erth5** [comment]
So, I'm waiting of the release *-*

**Comment by poychang** [comment]
![image](https://user-images.githubusercontent.com/4879879/84682741-ac46c480-af68-11ea-9121-9a93cd709f35.png)

delivery under the next version 😀
