### ISSUE TITLE
Sponsors dashboard not themed

### ISSUE THREAD

**Issue by janisozaur** [poychang/github-dark-theme#209]
Using Fx 78.0b6 and GitHub Dark Theme 1.1.2, the sponsors dashboard (`https://github.com/sponsors/<username>/dashboard/profile`) is not themed correctly.

![sb png](https://user-images.githubusercontent.com/550290/84603665-5bfc3380-ae90-11ea-9c86-eb1d77abc9b4.png)

**Comment by poychang** [comment]
I still under Sponsors waitlist. I can not see that page and fix that. If anyone who can help this fix that will be awesome.

**Comment by janisozaur** [comment]
I know little about TypeScript, unsure if I can help out with the code. I can send a redacted copy of that page.

**Comment by janisozaur** [comment]
Does this suffice:
![image](https://user-images.githubusercontent.com/550290/84700244-22d8c780-af53-11ea-933f-20ac3bd081b5.png)

```
.page-responsive .previewable-comment-form .comment-form-head.tabnav {
	background: #f6f8fa;
}
```

for the `Introduction` section

and

![image](https://user-images.githubusercontent.com/550290/84700386-5b78a100-af53-11ea-8f0a-4c4298fd74d4.png)
```
body :not(.commit-build-statuses) > a:not(.IssueLabel):not(.IssueLabel--big):not(.lh-condensed-ultra) {
	color: #d6d8da !important;
}
.MarketplaceEdit-body .menu-item {
	padding: 12px 16px;
	background: #fafbfc;
}
```

for the left side buttons?

Let me know if you need more info.

**Comment by IamCathal** [comment]
I am on github sponsors I'll look into this

**Comment by IamCathal** [comment]
@janisozaur Yes actually the fix was easier than you thought. I just selected the html element and tried to apply a new `background-color` attribute in my browser. Once I knew the element was correct I just searched for the class identifier in the code and either added in a `background-color` attribute or made a new css selector and added it in myself
