### ISSUE TITLE
Status button isn't themed on feature preview

### ISSUE THREAD

**Issue by Gangster8192** [poychang/github-dark-theme#211]
This status button isn't themed on the github feature preview (design updates)

![image](https://user-images.githubusercontent.com/30675315/85159908-19d64780-b22c-11ea-8b7f-268455921dc5.png)

**Comment by jiaming0708** [comment]
I can't find this button, could you post the page screenshot and url?

**Comment by Gangster8192** [comment]
It's on any github profile, such as my own (https://github.com/Gangster8192) but you have to have the github feature preview enabled.

![](https://givedino.money/sPb0Edcf31.png)

**Comment by Laiteux** [comment]
@Gangster8192 you have no status set, or at least I can't see it neither.

I have one set tho, check my profile.

**Comment by Gangster8192** [comment]
@Laiteux still there
![image](https://user-images.githubusercontent.com/30675315/85585916-71026080-b60e-11ea-93e4-bf683095f38c.png)

**Comment by Laiteux** [comment]
?

**Comment by Gangster8192** [comment]
The unthemed part is still there, even if there's a status set.

**Comment by Laiteux** [comment]
That's what I'm saying ;) I offered him to look at my profile because you had no status set.

**Comment by poychang** [comment]
This issue is fixed. Closed.
