### ISSUE TITLE
'Required' label doesn't show 

### ISSUE THREAD

**Issue by AmitShe** [poychang/github-dark-theme#212]
with GitHub new design the 'Required' label doesn't show, the color is close to the background color

![image](https://user-images.githubusercontent.com/38208025/85222827-db28c480-b3c6-11ea-9f8d-0a4b1dd237ac.png)

**Comment by jiaming0708** [comment]
could you post this PR link?

**Comment by EvaFro** [comment]
I am seeing the same thing.

**Comment by AmitShe** [comment]
> could you post this PR link?

**Comment by EvaFro** [comment]
Same ⬆️ otherwise I would post one also.

**Comment by jiaming0708** [comment]
I saw this issue on my repo, will fix it later

**Comment by jiaming0708** [comment]
fixed at https://github.com/poychang/github-dark-theme/commit/db07acee497b3bffd2514f63bd22d9c305f00e96 and released
