### ISSUE TITLE
Branch names not highlighted on selection

### ISSUE THREAD

**Issue by Ajay3598** [poychang/github-dark-theme#222]
The color contrast when a branch in drop down is selected is not present.

**Comment by poychang** [comment]
need more information or picture to point out where is the problem.

**Comment by IamCathal** [comment]
Are you talking about the currently moused over branch? I'd say it's fine and I'm on the latest github-dark-theme release on chrome. You cant see my cursor but I'm hovering over gh-pages

![](https://i.imgur.com/5U9KN0h.png)

**Comment by poychang** [comment]
Close this issue. Feel free to reopen if need more discourse.
