### ISSUE TITLE
[Feature] Add time period schedule base on local timezone to automatically switch to dark theme

### ISSUE THREAD

**Issue by iendeavor** [poychang/github-dark-theme#226]

**Comment by IamCathal** [comment]
This would be a very sudden change and I don't believe it'd be used by many people. If you're looking to have an experience that is nicer on your eyes overall I'd highly recommend using a blue light filter. It makes the harsh light much less harsh at night and I can't use my computer without it anymore. If you're on windows I'd reccoment [Flux](https://justgetflux.com/) or if you're on linux I'm currently using [Redshift](http://jonls.dk/redshift/).

Both have an option to scale the intensity of the filtering based on the time of day.
