### ISSUE TITLE
The dark theme does not work for the tags dropdown when comparing two commitish

### ISSUE THREAD

**Issue by kittaakos** [poychang/github-dark-theme#230]
This happens only for tags when comparing two commitish. See the screencast:

![screencast 2020-07-23 12-38-14](https://user-images.githubusercontent.com/1405703/88277810-a23f8080-cce1-11ea-8768-8a7af226b8e5.gif)

Works perfectly when browsing branches and tags:
![screencast 2020-07-23 12-38-58](https://user-images.githubusercontent.com/1405703/88277854-b1bec980-cce1-11ea-9983-e46efecee3f5.gif)

Version: `1.1.7`
Browser: Brave `Version 1.11.97 Chromium: 84.0.4147.89 (Official Build) (64-bit)`.

----
My eyes really appreciate this great library, thank you! 🙏

**Comment by poychang** [comment]
fix on next version

**Comment by kittaakos** [comment]
Wow, thank you!

It works with `1.1.8`.
