### ISSUE TITLE
Styling doesn't apply to Github Hovercard extension

### ISSUE THREAD

**Issue by chrismessina** [poychang/github-dark-theme#231]
![image](https://user-images.githubusercontent.com/22610/88443888-258ad000-cdcf-11ea-93f3-7ff67c1486d7.png)

This might be more of a feature request, but it would be great if the styling extended to [this extension's](https://chrome.google.com/webstore/detail/github-hovercard/mmoahbbnojgkclgceahhakhnccimnplk) hovercards.

**Comment by poychang** [comment]
now you can expect next version 😄
