### ISSUE TITLE
Styling of the insights traffic page seems to be a bit wrong

### ISSUE THREAD

**Issue by Elandig** [poychang/github-dark-theme#232]
`github.com/<username/organization>/<repo>/graphs/traffic`
![image](https://user-images.githubusercontent.com/15586732/88582382-4e24fb00-d057-11ea-8afc-e99e4c61f7cd.png)

**Comment by Elandig** [comment]
`github.com/<username/organization>/<repo>/graphs/network`
![image](https://user-images.githubusercontent.com/15586732/88582870-0bafee00-d058-11ea-9a70-4aab39ec4bd0.png)
Styling of the 'Network' tab has issues as well, though I don't know if you could modify the canvas element. Don't mind the branch name, I edited it out myself.

**Comment by poychang** [comment]
I can style Network graph like this
![image](https://user-images.githubusercontent.com/4879879/88610586-a391f400-d0b9-11ea-84df-c3364f807278.png)

**Comment by Elandig** [comment]
> styling canvas is limited. but I can style Network graph like this
> ![image](https://user-images.githubusercontent.com/4879879/88610586-a391f400-d0b9-11ea-84df-c3364f807278.png)

Looks much better. Thank you
