### ISSUE TITLE
visibilitty-with-third-party-extentions

### ISSUE THREAD

**Issue by FatTonyy** [poychang/github-dark-theme#236]
[Example](https://res.cloudinary.com/dcbx7o2dn/image/upload/v1597148820/fat-tonyy/Screenshot_1_hlbyrq.png)

an extension like [Github Original Streak] becomes invisible when the dark theme extension is activated

**Comment by IamCathal** [comment]
The extension works through targeting class attributes to alter the styles of them. To add functionality for other extensions there would have to be code in the codebase that most people would probably never need. However implementing this functionality to be able to use the original streak extension would be quite simple.

All I needed to add was this
```css
.contrib-number, .text-muted {
    color: $text-color !important;
}

**Comment by FatTonyy** [comment]
please do
