### ISSUE TITLE
New notifications: a notification with focus and toast notification have default background

### ISSUE THREAD

**Issue by maksimovic** [poychang/github-dark-theme#237]
<img width="1675" alt="Notifications" src="https://user-images.githubusercontent.com/1126226/90005087-fe6d4300-dc96-11ea-8181-cf37aedc79b4.png">

**Comment by poychang** [comment]
I do not know when will happen this. Do you mean when notification toasted the new message on the top is not theme?
![image](https://user-images.githubusercontent.com/4879879/90841217-b7fe9f00-e38e-11ea-80eb-6f2fd6735c14.png)

**Comment by poychang** [comment]
Do you install any other extension? I can not find the "Mark ad done" button.
I did try several time, and I still can not find the problem.
If that is cause by other extension, we can add custom change for this issue. Just like [those extensions](https://github.com/poychang/github-dark-theme/blob/develop/src/theme/extensions/!ext.scss)

**Comment by maksimovic** [comment]
No, it's Github's **_new_** notifications, but probably you are not using feature preview. There's updated notifications view which, it seems, is not rolled out for everyone yet.

**Comment by IamCathal** [comment]
As Dive said in https://github.com/poychang/github-dark-theme/issues/261 he found the bug when he was using the j and k keys to select issues. I couldn't get the bug to show without doing this but I assume it will fix the selected notification error
