### ISSUE TITLE
Invisible title when visiting issue from a notification

### ISSUE THREAD

**Issue by apiraino** [poychang/github-dark-theme#238]
Example: https://github.com/seanmonstar/warp/issues/681

When viewed from usual URL title has color `#9da5b4`

![2020-08-17_135031](https://user-images.githubusercontent.com/6098822/90393305-c304b700-e090-11ea-9a06-27ba6a26e0e2.png)

When reaching that issue from my github notifications, title has color `#24292e`

![2020-08-17_135047](https://user-images.githubusercontent.com/6098822/90393359-ddd72b80-e090-11ea-85f3-c175b2e542b0.png)

Is that something that this extension should handle?

By the way - really nice extension, thanks!

**Comment by IamCathal** [comment]
Odd, I've not experienced this problem. What browser are you on? Maybe try reloading or reinstalling the extension and seeing if the problem persists.

The default title text color is `#24292e` so there must be some issue with the title not being overridden when loading from notifications

**Comment by apiraino** [comment]
uhm ... interesting :thinking: I've restarted the browser and now can't reproduce anymore ¯\\_(ツ)_/¯ 

For the record I am using: Firefox 80.0b8 on Ubuntu 19.10

I'll close this issue and be back in case I have a more reproducible case.

Thanks!
