### ISSUE TITLE
Possibility to choose theme preset.

### ISSUE THREAD

**Issue by fabiocaccamo** [poychang/github-dark-theme#241]
I just discovered the https://github.com/mrivnak/github-dracula-theme by @[mrivnak](https://github.com/mrivnak), the theme colors are beautiful but the repository is not up-to-date with this one, so there are many small things to fix.

It would be nice if this theme would support multiple color themes (including the github-dracula-theme colors), giving the option to select which one to use.

**Comment by poychang** [comment]
Nice extension. Themes selector is good, but need more effort to accomplish.
Note this [commit](https://github.com/mrivnak/github-dracula-theme/commit/06c666b33e11cb8c6b38dcbe9dac8fd16e209847) for how many places need extract colors to variables.scss
Thanks for your share.
