### ISSUE TITLE
[GitHub Actions]: Dark theme is not applied on the 'workflow_dispatch' label

### ISSUE THREAD

**Issue by kittaakos** [poychang/github-dark-theme#242]
If your GH Action can be triggered with `'workflow_dispatch'`, you will see the following with the default GH theme:

![Screen Shot 2020-08-24 at 14 43 16](https://user-images.githubusercontent.com/1405703/91046143-3752d380-e618-11ea-8dc8-8942cc780f13.jpg)

And this is what you will get with the dark theme:

![Screen Shot 2020-08-24 at 14 40 53](https://user-images.githubusercontent.com/1405703/91046249-5cdfdd00-e618-11ea-9441-378c57a850a1.jpg)

I am not sure if it's possible to solve, but manually unsetting the `background` of the HTML element (from DevTools) improves the UX.

![Screen Shot 2020-08-24 at 14 45 43](https://user-images.githubusercontent.com/1405703/91046361-931d5c80-e618-11ea-82e3-464b201906d9.jpg)

**Comment by guibranco** [comment]
The same problem here!

![image](https://user-images.githubusercontent.com/3362854/91088821-0dee7380-e629-11ea-8de6-36f30cd9b714.png)

**Comment by guibranco** [comment]
Using `#676d79` should be cool enough

![image](https://user-images.githubusercontent.com/3362854/91089253-b1d81f00-e629-11ea-994b-6da7c1953da5.png)

**Comment by IamCathal** [comment]
I'll submit a PR for this tonight when I'm free
