### ISSUE TITLE
Invitation page is not shown correctly

### ISSUE THREAD

**Issue by spadeloves** [poychang/github-dark-theme#249]
On invitation page for organization, the group names are not shown correctly.

![chrome_QUEN2tPzrS](https://user-images.githubusercontent.com/11781291/94232564-3e377380-ff41-11ea-85df-410db5febd70.png)

Team detail text is shown but title of team is not shown.

**Comment by IamCathal** [comment]
I see some broken things and I'll submit a PR for them when I get the chance. How exactly do you get to that page that you linked above?

**Comment by spadeloves** [comment]
@IamCathal 

> I see some broken things and I'll submit a PR for them when I get the chance. How exactly do you get to that page that you linked above?

You can see this on "Invite Member" of organization that has one own team at least.
https://github.com/orgs/[Your Organization Name]/people

after choose the account to invite, Github asks which role to assign to the new member. On that screen, you can choose the teams which the new member will join. (if there is no team in the organization, this part is not shown.)
This part is on that page. I added the full screenshot.

![chrome_QB3yJwNz5T](https://user-images.githubusercontent.com/11781291/94411548-ac836c80-01b3-11eb-9270-c00c87add07a.png)

I think I can fix this too, so I'll work with this too.
