### ISSUE TITLE
Problem in viewing the contribution graph.

### ISSUE THREAD

**Issue by achaljhawar** [poychang/github-dark-theme#250]
![issue](https://user-images.githubusercontent.com/35405812/94361966-a919b380-00d5-11eb-8df7-a9bbf3c501a4.JPG)

**Comment by IamCathal** [comment]
I can't tell what you mean. Do you mean the problem is that on the far right that there is only one dot? That's intended and it looks the same without the extension as seen below

![no extension screenshot](https://i.imgur.com/n8p5EhI.png)

**Comment by achaljhawar** [comment]
No, I can properly see it.

**Comment by achaljhawar** [comment]
It's quite lighter in the page with extension

**Comment by IamCathal** [comment]
So you don't like the actual shade of the colors? I've never had a problem with it but if you want your own color scheme like I've done with mine below you just need to change the color code on [this](https://github.com/poychang/github-dark-theme/blob/62cdf27c0dbe00f5c41e2f6532035cac92bd2b01/src/theme/variables.scss#L60) line to whatever color code you want. This color will be the darkest and the rest are lightened by 30%, 50% etc to get the lighter days. If you have any problem doing this give me a shout and I'll be happy to help :)
![](https://i.imgur.com/6GmaKrU.png)

**Comment by achaljhawar** [comment]
Thanks helped a lot
