### ISSUE TITLE
Background of the selected item on GitHub Notifications page is white

### ISSUE THREAD

**Issue by dive** [poychang/github-dark-theme#261]
Hello there,

Thanks for the extension!
There is a problem on the [Notifications](https://github.com/notifications) page, background of the selected item is white when you **navigate items with keyboard** shortcuts (j/k).

Browser: Firefox 82.0b9 (64-bit)

<img width="911" alt="Screenshot 2020-10-11 at 00 23 55" src="https://user-images.githubusercontent.com/59749/95667046-76050480-0b58-11eb-95ad-2767d247794d.png">

**Comment by IamCathal** [comment]
Might be related to https://github.com/poychang/github-dark-theme/issues/237

I'll look into it now and see what the story is.
