### ISSUE TITLE
A slightly curious part of the Incremental Search Window

### ISSUE THREAD

**Issue by TakahisaHayashi** [poychang/github-dark-theme#263]
Hello. I was wondering a little bit about the colors used for "in this repository", "All GitHub", and "Jump to" in the incremental search window, which seems a little darker.
If you look at the image, you'll see what I mean.
I'd like to submit a pull request if you'd like, what do you think? 

## Present
![image](https://user-images.githubusercontent.com/57127872/95766847-d7f77280-0cee-11eb-9529-eadd4b20252e.png)

## When fixed, it looks like this
![image](https://user-images.githubusercontent.com/57127872/95766818-ca41ed00-0cee-11eb-9f45-e5c60bb66815.png)

Thank you.

**Comment by IamCathal** [comment]
Related to https://github.com/poychang/github-dark-theme/issues/264

As I said in my response I think a project wide change to the muted text colors should be introduced or atleast tried out in a PR.

**Comment by TakahisaHayashi** [comment]
Yes, I understand.
I'll send out a pull request. I hope to be able to discuss it there.
Best Regards.
