### ISSUE TITLE
Refined GitHub

### ISSUE THREAD

**Issue by j0hnmeow** [poychang/github-dark-theme#273]
Support [Refined GitHub](https://github.com/sindresorhus/refined-github). Currently it has some issues with some things not being themed
![Example](https://user-images.githubusercontent.com/43097806/96840427-1dd0db00-1453-11eb-8486-2fe48c7dbffc.png)

**Comment by EvaFro** [comment]
This includes things like text boxes also.
<img width="1092" alt="Screen Shot 2020-10-23 at 9 40 58 AM" src="https://user-images.githubusercontent.com/24962853/97030700-03126b00-1514-11eb-9da5-db99fffb3d0f.png">
<img width="712" alt="Screen Shot 2020-10-23 at 9 40 48 AM" src="https://user-images.githubusercontent.com/24962853/97030705-04dc2e80-1514-11eb-990f-4218d34437c5.png">

**Comment by alazymeme** [comment]
> This includes things like text boxes also. So the Approval box and the comment box.
> *images*

I don't believe this has to do with refined github, since I don't have refined github and i have the same issue. Could you please create a new issue?

![image](https://user-images.githubusercontent.com/12804673/97063900-c151f500-15e5-11eb-86d2-865a765721b7.png)
