### ISSUE TITLE
Weird Styling in all text boxes. 

### ISSUE THREAD

**Issue by EvaFro** [poychang/github-dark-theme#279]
Weird white box around text boxes. Including small corner pieces.  Here are images of the the Approval box and the comment box. 
<img width="1092" alt="Screen Shot 2020-10-23 at 9 40 58 AM" src="https://user-images.githubusercontent.com/24962853/97030700-03126b00-1514-11eb-9da5-db99fffb3d0f.png">
<img width="641" alt="Screen Shot 2020-10-23 at 9 43 18 AM" src="https://user-images.githubusercontent.com/24962853/97030848-3e149e80-1514-11eb-9e9f-cf09070e6b55.png">

_Originally posted by @EvaFro in https://github.com/poychang/github-dark-theme/issues/273#issuecomment-715452413_

**Comment by EvaFro** [comment]
Looks like this is related to issue #278.

**Comment by RedSparr0w** [comment]
Are you running `v1.1.16`?
As I believe this was fixed in #275

**Comment by EvaFro** [comment]
yes you are correct its fixed.
