### ISSUE TITLE
Saved replies issue

### ISSUE THREAD

**Issue by guidezpl** [poychang/github-dark-theme#287]
The saved replies show up weird, but only with the extension turned on

<img width="667" alt="Screenshot 2020-11-03 at 11 59 00" src="https://user-images.githubusercontent.com/6655696/97977181-19e67680-1dcc-11eb-8c81-f40d5ec340ae.png">
<img width="667" alt="Screenshot 2020-11-03 at 11 58 44" src="https://user-images.githubusercontent.com/6655696/97977193-1e129400-1dcc-11eb-9869-1c12611110b6.png">

**Comment by poychang** [comment]
![image](https://user-images.githubusercontent.com/4879879/99017450-eb6a5780-2592-11eb-8c1c-f97f6751b93d.png)
No idea... It works fine with me.

**Comment by guidezpl** [comment]
Try it in a PR review
