### ISSUE TITLE
Miss support .project-card selector

### ISSUE THREAD

**Issue by immuzov** [poychang/github-dark-theme#290]
I think some styles are missing for the issue card on the project board.

![image](https://user-images.githubusercontent.com/3313023/98334900-607edf80-201d-11eb-8600-e1ea09c54dc7.png)

Same problem with issue details:
![image](https://user-images.githubusercontent.com/3313023/98335149-e00cae80-201d-11eb-8a15-78e9bbfd593a.png)

**Comment by dwSun** [comment]
+1

**Comment by IamCathal** [comment]
I was using a project board a day or two ago and it was fine but I just checked there and it is broken for me. I'm on chrome btw

**Comment by dannyalan** [comment]
This is a recent thing, I have just noticed it today too
