### ISSUE TITLE
Add support for Github enterprise

### ISSUE THREAD

**Issue by LunaticoCR** [poychang/github-dark-theme#31]
Hello,

This Firefox extension looks amazing! But I can't really use it because I use Github enterprise and the base url does not match ```*.github.com*```.
Have you considered adding support for users to change the base url?
I tried to change it on the manifest file inside the .xpi but that breaks the signature.

Thanks!

**Comment by poychang** [comment]
Make it work with GitHub Enterprise is the top  of wish list. I’ll try to make it happen.

**Comment by poychang** [comment]
Hi @LunaticoCR,

Can you help me to test the Github enterprise feature? Download the zip file below and install in your Chrome. You can modify the domain list on the menu icon. If you have any question, please let me know, thanks you!

[dist-chrome.zip](https://github.com/poychang/github-dark-theme/files/3421530/dist-chrome.zip)

![menu icon](https://user-images.githubusercontent.com/4879879/61704881-5036e880-ad77-11e9-8b7a-a06b1732d924.png)

**Comment by LunaticoCR** [comment]
I just loaded it and it's looking good.

**Comment by poychang** [comment]
Awesome! Let me refactoring some code, and I’ll release this feature ASAP.
