### ISSUE TITLE
Arrow indicator on comment reactions are white

### ISSUE THREAD

**Issue by albinpk** [poychang/github-dark-theme#325]
Shows white color arrow for Pick reaction popup

![Screenshot 2020-12-02 225825](https://user-images.githubusercontent.com/56157868/100909434-bc406980-34f2-11eb-8326-b84ba4531d20.png)

**Comment by poychang** [comment]
![image](https://user-images.githubusercontent.com/4879879/101918095-eafdc480-3c03-11eb-8dda-8aa93cec5987.png)
can not find that white arrow

**Comment by albinpk** [comment]
Still have the white arrow.
But that's not a big problem 🙂


![Screenshot 2020-12-12 144650](https://user-images.githubusercontent.com/56157868/101980182-addc1580-3c89-11eb-802c-43bf1fe6ad08.png)
