### ISSUE TITLE
Weird White Bar on Pull Request Page

### ISSUE THREAD

**Issue by EvaFro** [poychang/github-dark-theme#328]
Today a weird white bar showed up on the Pull Request page
<img width="1775" alt="Screen Shot 2020-12-08 at 10 28 59 AM" src="https://user-images.githubusercontent.com/24962853/101525567-56177480-3940-11eb-9953-e4e408882337.png">

**Comment by Bavfalcon9** [comment]
This is an issue on all pages. The footer has been changed from what it looks like 🤔

**Comment by Bavfalcon9** [comment]
Looks like they rolled out darkmode: https://github.com/settings/appearance

**Comment by EvaFro** [comment]
interesting. Ok Thanks. I just put the dark mode on and it disappeared 😜
