### ISSUE TITLE
Make <html> and <body> tag, height 100% to avoid white background

### ISSUE THREAD

**Issue by OlivierCo** [poychang/github-dark-theme#335]
The following tags `<html>` and `<body>` must be of height 100% as you can see on the screen shot without it you have a white background that is appearing.

<img width="1102" alt="Screenshot 2020-12-27 at 16 17 18" src="https://user-images.githubusercontent.com/1804322/103175061-24b70800-485f-11eb-8367-772696954bc8.png">

With height: 100% apply to `<html>` and `<body>`

<img width="1102" alt="Screenshot 2020-12-27 at 16 20 52" src="https://user-images.githubusercontent.com/1804322/103175107-80819100-485f-11eb-8433-914966e70776.png">

**Comment by IamCathal** [comment]
Was fixed in https://github.com/poychang/github-dark-theme/pull/330 so you should see the change soon :)
