### ISSUE TITLE
Github styles might have change today - unchanged lines have white background

### ISSUE THREAD

**Issue by dbrennan** [poychang/github-dark-theme#339]
Dark theme was working great this morning, and sometime after lunch unchanged lines in PRs now have a white background:

example:

![image](https://user-images.githubusercontent.com/7130461/105102829-4ffad480-5a64-11eb-8ca3-a266c6278f7f.png)

**Comment by mpanchap** [comment]
Yes for me too. I've disabled it for now. Will follow this ticket until resolved.

**Comment by IamCathal** [comment]
Working on a fix right now, will have it ready in a few

**Comment by dbrennan** [comment]
Awesome, the Github dark mode is too bright in the highlights

**Comment by zachariapopcorn** [comment]
Had this issue as well, hopefully it gets resolved

**Comment by mathieumuller** [comment]
Same white background for review comments. Great work by the way 👏

**Comment by ferdn4ndo** [comment]
Confirming that version `1.1.23` for Chrome is failing for unchanged lines background:

![image](https://user-images.githubusercontent.com/21228400/105214136-5e152780-5b2e-11eb-8fc1-f74414893714.png)

**Comment by luispabon** [comment]
Thank you, #340 indeed fixed it for me.

**Comment by ferdn4ndo** [comment]
Version 1.1.24 is still failing for me, now in a new place - when the file is too big to be shown:

![image](https://user-images.githubusercontent.com/21228400/105411950-d7864600-5c12-11eb-8384-2c41c36931cd.png)

Should I open another PR?

**Comment by IamCathal** [comment]
@ferdn4ndo could you please link a commit (or PR?) where the diff is too big to be displayed so I can give it a go fixing it?

**Comment by poychang** [comment]
![image](https://user-images.githubusercontent.com/4879879/105566072-204e1400-5d65-11eb-98d2-cb216f3aaa77.png)

@ferdn4ndo you can use this extension with official dark theme to fix that issue
@IamCathal here is sample https://github.com/poychang/github-dark-theme/pull/28/files
