### ISSUE TITLE
Refresh button color need some improvement

### ISSUE THREAD

**Issue by kristiantoyanuar** [poychang/github-dark-theme#34]
![image](https://user-images.githubusercontent.com/16025910/61363814-3436d100-a8b7-11e9-8bf6-6067a09155b0.png)

**Comment by poychang** [comment]
Is this refresh button originally available?

**Comment by kristiantoyanuar** [comment]
It will show up when you create PR, then thr PR become outdated when new commit pushed.

**Comment by poychang** [comment]
Done! Check it out 😃

**Comment by kristiantoyanuar** [comment]
thanks man, dope!
i hope i could contribute some in the future, cheers
