### ISSUE TITLE
Pull Request diff-viewer showing glaring white-background

### ISSUE THREAD

**Issue by amitSA** [poychang/github-dark-theme#342]
Just recently I noticed that the pull-request diff-viewer is showing a glaring white background
![image](https://user-images.githubusercontent.com/7193781/105284884-32169800-5b68-11eb-90ff-041b0744803a.png)
[Link to above](https://github.com/torvalds/linux/pull/805/files)

I disabled this extension and the white-background went away.   If others aren't experiencing this, then its possible another one of my extensions is interfering with this one.

**Comment by Aydinhepsaydir** [comment]
I found when turning on the Github dark theme, found [here](https://github.com/settings/appearance), the "glaring white background" disappeared when using this extension.

**Comment by ferdn4ndo** [comment]
This section was fixed with #340, although I confirm that there's still an issue when the file is too big (see my comment [here](https://github.com/poychang/github-dark-theme/issues/339#issuecomment-764939992))

**Comment by poychang** [comment]
@Aydinhepsaydir combine official dark theme with this can make theme more fine 😅

**Comment by poychang** [comment]
@amitSA it works fine in my setting, official white theme with this extension. try to disable other extension may helps to find the root cause. 

![image](https://user-images.githubusercontent.com/4879879/105566297-5e980300-5d66-11eb-96e7-bfee4b9061b8.png)

**Comment by amitSA** [comment]
The suggestion from others to turn on the official dark-theme with this extension resolves the original problem. 
Closing this ticket, thanks everyone
