### ISSUE TITLE
white band on repository name

### ISSUE THREAD

**Issue by vhnguyenae** [poychang/github-dark-theme#345]
Hello, I'm using Firefox v86.0 on Ubuntu, 
There is a white band on the repostiory name
I don't think I saw it before, may be recently only
Could some one check if it's a bug or it's expected to be like this?
Thanks in advance,
Vu Hai
![image](https://user-images.githubusercontent.com/60604412/110675340-0f514900-81d3-11eb-9933-3294aabc933b.png)

**Comment by KatieProchilo** [comment]
Also was experiencing this on Edge but it just resolved for me
