### ISSUE TITLE
Why does Chrome extension need read/change permissions for all websites ?

### ISSUE THREAD

**Issue by le0nik** [poychang/github-dark-theme#35]
What is the reason for this change in persmissions in latest version?

https://github.com/poychang/github-dark-theme/blob/11e4918c0eb65a18a9881e90be68d045d511c0c7/src/manifest/manifest-chrome.json#L16-L19

Thanks for your work btw!

**Comment by poychang** [comment]
For the feature which can store custom domain. Lots of people want to add their GitHub Enterprise domain.

**Comment by le0nik** [comment]
Got it, thanks. Maybe it would make sense to add this to the release notes so that users looking for the reason for warning in Chrome know why this is needed?

**Comment by poychang** [comment]
Good suggest! Thanks 😀
