### ISSUE TITLE
Can not find GitHub Dark Theme in Chrome web store, it's been marked unsafe？

### ISSUE THREAD

**Issue by dannypc1628** [poychang/github-dark-theme#352]
我的瀏覽器跳出通知說：這個擴充功能已被標記為不安全，去Store看也找不到

請問是發生什麼事了嗎？？？

Browser notify 'This extension has been disabled because it's been marked unsafe by the Chrome Web Store.'

Now ,Can't find in Chrome web store. What’s happening？

**Comment by ysquaredd** [comment]
I'm seeing the same thing too :(

**Comment by MrBartusek** [comment]
Can confirm, extension stopped working today, disappeared from extensions bar

**Comment by esatterwhite** [comment]
you can still re-enable it from the `chrome://extensions` if it were previously installed

**Comment by MattRiddell** [comment]
Yeah, but why was it marked unsafe?

**Comment by IamCathal** [comment]
This is quite sad :(

As @esatterwhite said you can still use the extension. You've just got to download, build and load it as an unpacked extension (atleast for chrome). [Heres how to do it on chrome](https://webkul.com/blog/how-to-install-the-unpacked-extension-in-chrome/)

**Comment by SlipperyPete79** [comment]
@poychang Can you shed some light as to why this plugin was blacklisted?

**Comment by poychang** [comment]
Sorry for late reponse and this issue.
Chrome web store removed this extension for safety reasons, to be precise, this extionstion has broad host permissions (<all_urls>) in mainifest.json. And that's why you saw "unsafe" worning on browser.
I'll try to contact Chrome web store team and explain why this extension needs this permission.

**Comment by SlipperyPete79** [comment]
Thanks for the clarification

**Comment by poychang** [comment]
Good news about this issue.
> The submission is approved and the latest version of the extension will be published in the Chrome Web Store shortly.
From Chrome web store team.
