### ISSUE TITLE
Monospace links do not look like links

### ISSUE THREAD

**Issue by denis-itskovich** [poychang/github-dark-theme#375]
Links, using monospace formatting do not have link colors and underline. For example:

[`This text should be displayed as link`](#none)

In default (white) scheme, links using monospace have usual link colors and underline, but not in dark theme

**Comment by RyanPatch646** [comment]
noticed this as well and came here to see if it was reported

**Comment by lobsterkatie** [comment]
Any news on this? Thanks!

**Comment by lobsterkatie** [comment]
Thanks, @huyenltnguyen!
