### ISSUE TITLE
developer.github.com renders poorly with this extension

### ISSUE THREAD

**Issue by jwbusch** [poychang/github-dark-theme#38]
![image](https://user-images.githubusercontent.com/9566946/62991415-283a2280-be15-11e9-81db-ac99a41dcab4.png)

https://developer.github.com/actions/

I know this extension is mostly for the main repo view, but it gets enabled on the developer portal for github too. It would be nice to be able to add subdomains that could be excluded. (or fix the rendering of the developer portal, but I figure exclusion is easier)

Thanks!

**Comment by poychang** [comment]
I will use a more rigorous way to compare domains to avoid subdomains being styled.
