### ISSUE TITLE
Contributions table is too bright

### ISSUE THREAD

**Issue by Prifiz** [poychang/github-dark-theme#41]
![image](https://user-images.githubusercontent.com/5525317/63471923-a2a41b80-c481-11e9-9828-53612de8c210.png)
It would be great if background of this widget became more dark. Now it is contrasting with the background

**Comment by poychang** [comment]
That table accurately is SVG not html. It's that possible change SVG background color by CSS?

**Comment by Prifiz** [comment]
Oh... It's not a background but default color for no contributions.. You're right, it might be not so simple to fix.

**Comment by vinyldarkscratch** [comment]
CSS can easily change any SVG property by design, actually.  Rather than set a background color, we'd be looking at setting the `fill`.  Essentially, we could have a `rect[fill="#XXYYZZ"]` selection that modifies the colors, though something implemented like this is more than likely to show issues pretty quickly.  Using CSS' `attr()` function doesn't seem to work either.  Unfortunately, looking around the DOM, it doesn't seem like there's much else we could do...

**Comment by tariq86** [comment]
How does this look?

![contributions_updated](https://user-images.githubusercontent.com/646561/64632580-f1790d00-d3be-11e9-96bf-810fb7067d38.png)

This is with 0 contributions set to `$text-color`, and 15% darker for each color level.  In other words:
 * 0 Contributions: `$text-color`
 * 1-4 Contributions: `darken($text-color, 15%)`
 * 5-9 Contributions: `darken($text-color, 30%)`
 * 10-13 Contributions: `darken($text-color, 45%)`
 * \>=14 Contributions: `darken($text-color, 60%)`

I'm open to suggestions for the base color and step %

**Comment by vinyldarkscratch** [comment]
Personally, I think that we should invert the order of colors, and keep the moss green hue that GitHub already has, so it feels more like the standard coloring users are already accustomed to.  In other words, 0 contributions would be the darkest at almost purple black, and then >=14 contributions would be the pure green.  Of course, that’s just my own opinion!

**Comment by poychang** [comment]
I have the same opinion with @vinyldarkscratch. I feel comfortable with green.

**Comment by tariq86** [comment]
How about this?

### Option 1:
![contrib_02](https://user-images.githubusercontent.com/646561/64662276-72f78c00-d40d-11e9-8e70-58ebb412ab27.png)

 * 0 Contributions: `#767676`, same as month labels at the top
 * 1-4 Contributions: `lighten(#196127, 50%);`
 * 5-9 Contributions: `lighten(#196127, 30%);`
 * 10-13 Contributions: `lighten(#196127, 15%);`
 * 14+ Contributions: `#196127`, the original dark green

### Option 2: same as above, but with black for 0 contributions:
![contrib__3](https://user-images.githubusercontent.com/646561/64662421-0cbf3900-d40e-11e9-97e5-e5a47f8a14a5.png)

**Comment by vinyldarkscratch** [comment]
I think black has a higher contrast, which helps the content stand out more, so I'm leaning towards that.  As I mentioned before though, we should invert the direction of the colors.  In other words, "brighter is more contributions".  This will maintain a more consistent coloring scheme, as our gradient ramp would only be heading in one direction, rather than suddenly changing for the very first part.

Here is what I propose:

0 Contributions: `#767676` OR `black` (or potentially `darken(#196127, 15%)`)
1-4 Contributions: `#196127`
5-9 Contributions: `lighten(#196127, 15%)`
10-13 Contributions: `lighten(#196127, 30%)`
14+ Contributions: `lighten(#196127, 50%)`

**Comment by tariq86** [comment]
How does this look?

![contrib__5](https://user-images.githubusercontent.com/646561/64666701-d4732700-d41c-11e9-81b0-fc2e8e89e350.png)

**Comment by Prifiz** [comment]
Looks a little bit confusing.
IMHO the original "more contributions - the darker color" should be left as-is.
For the picture above, it seems like the darker rects near the lighter ones are representing more contributions.

**Comment by vinyldarkscratch** [comment]
Hmm, I guess you have a point, as the denser, darker colors visually represent “more” to users...  This is going to be a tough one to make look right!

Perhaps the initial option 2 suggested is the best bet.  Thanks @tariq86 for playing around with the colors and showing examples for us!

**Comment by tariq86** [comment]
No problem @vinyldarkscratch! I wanted to make sure we all agreed on a style before submitting the PR. I'll do that later today, with option 2 in [this comment](https://github.com/poychang/github-dark-theme/issues/41#issuecomment-530187489).

**Comment by tariq86** [comment]
Pull request created!

**Comment by poychang** [comment]
Thanks for discussion and contribution. Specially @tariq86 PR awesome code make this work 👍

**Comment by Prifiz** [comment]
Hmm... something went wrong.
It's still looking like it was before fix:
![image](https://user-images.githubusercontent.com/5525317/65263686-2f440700-db1e-11e9-8eac-6f9041c742e1.png)

**Comment by tariq86** [comment]
The base color was reverted in commit c3803894c7532cee772ddf5db1c8b29b411e8fa5 after issue #57 was opened because it was too confusing.

**Comment by Peter92** [comment]
> How does this look?
> 
> ![contributions_updated](https://user-images.githubusercontent.com/646561/64632580-f1790d00-d3be-11e9-96bf-810fb7067d38.png)

I actually really like the colour scheme of this one, but it's definitely quite confusing. I think there's a chance it could work inverted, with the dark black being changed to something that matches the background a little better

**Comment by MERZAK-X** [comment]
> How about this?
> 
> ### Option 1:
> ![contrib_02](https://user-images.githubusercontent.com/646561/64662276-72f78c00-d40d-11e9-8e70-58ebb412ab27.png)
> 
> * 0 Contributions: `#767676`, same as month labels at the top
> * 1-4 Contributions: `lighten(#196127, 50%);`
> * 5-9 Contributions: `lighten(#196127, 30%);`
> * 10-13 Contributions: `lighten(#196127, 15%);`
> * 14+ Contributions: `#196127`, the original dark green
> 
> ### Option 2: same as above, but with black for 0 contributions:
> ![contrib__3](https://user-images.githubusercontent.com/646561/64662421-0cbf3900-d40e-11e9-97e5-e5a47f8a14a5.png)

>> Option 1 is good option, **not confusing** at all , better than nothing tho 😕
