### ISSUE TITLE
Make URLs clickable

### ISSUE THREAD

**Issue by Prifiz** [poychang/github-dark-theme#42]
The first thing I tried to do after configuring the github URL in this extension is clicking upon this URL to open the github. But oops... it's only a plain text.
Could you please reformat it as a reference. It would be extremely useful and time-saving to open github from there
![image](https://user-images.githubusercontent.com/5525317/63472217-7e950a00-c482-11e9-924e-a0f3b9f27cb0.png)

**Comment by poychang** [comment]
@Prifiz extension does not support gitlab. It is reasonable to make it clickable. I will add this feature in the near future. Thank your.

**Comment by Prifiz** [comment]
@poychang of course I meant github, corrected the description

**Comment by poychang** [comment]
update to 1.0.14 and it's work! 😎

**Comment by Prifiz** [comment]
@poychang perfect! Thanks a lot!
