### ISSUE TITLE
Option to opt out dark mode for Github pages

### ISSUE THREAD

**Issue by tylerstuff** [poychang/github-dark-theme#45]
Hi there! I'm a huge fan of using Github Dark Theme (especially for on enterprise). One thing that would like to suggest is if we can have an option to disable dark mode for Github Pages. For  instance if my enterprise github url is enterprisegithub.com, Github Pages are displayed as enterprisegithub.com/pages/username/slides. With the current implementation, because the domain is the same, dark theme is used in github pages which may cause visibility issues for pages with custom font colors. If we can opt out on certain trails in the URL that would make this really awesome!

**Comment by poychang** [comment]
Thank you for your use. Glad you like it. You mean exclude some URL from GitHub Enterprise domain which like document pages. I think it can be done with exclude list feature. I'll figure it out.

**Comment by stychu** [comment]
+ 1 For this. I've to disable the extension every time I visit Github pages. Super annoying
