### ISSUE TITLE
TimelineItemBreak class not styled correctly.

### ISSUE THREAD

**Issue by gapark** [poychang/github-dark-theme#49]
The css class `TimelineItem-break` is currently still styled with a white background. This needs updating to match the rest of the theme.

Currently looks as shown in below image:
![image](https://user-images.githubusercontent.com/38913345/64346394-f407eb00-cfe9-11e9-9edd-dafd454cf85a.png)

Should appear as:
![image](https://user-images.githubusercontent.com/38913345/64346598-4f39dd80-cfea-11e9-8e92-6269a4081434.png)

**Comment by poychang** [comment]
v1.0.17 had fix this issue.
