### ISSUE TITLE
Text color in comments are black in dark theme

### ISSUE THREAD

**Issue by JoshuaRogan** [poychang/github-dark-theme#50]
The font color for PR comments used to be white but with a recent GitHub update, it now appears black in the dark theme. Could be black in other places as well. 
See: https://share.getcloudapp.com/7Ku2Zlbr

**Comment by 333fred** [comment]
It's also black in issue comments.

**Comment by ezzygemini** [comment]
I can't see what the above comments say because they're black.

**Comment by leomotta121** [comment]
Can't read anything black on black as well.

**Comment by poychang** [comment]
Thanks all of you report this issue. I fixed this. Please wait v1.0.18 version publish.

**Comment by leomotta121** [comment]
@poychang Thank you!

**Comment by zeldrinn** [comment]
@poychang thanks for the quick fix! Any idea when v1.0.18 will be published?

**Comment by poychang** [comment]
> @poychang thanks for the quick fix! Any idea when v1.0.18 will be published?

I published yesterday, but still wait for Google review now...

**Comment by poychang** [comment]
For temporally, you can manual download and install v1.0.19 from [here](https://github.com/poychang/github-dark-theme/releases/tag/v1.0.19).

**Comment by poychang** [comment]
The longest publish wait I ever wait. This issue should be fix on v1.0.19, the latest version.

**Comment by zeldrinn** [comment]
@poychang thanks! Strange though, I uninstalled and reinstalled the extension with latest version and I'm still having the same issue. Cleared cache as well.

**Comment by zeldrinn** [comment]
@poychang Thanks, though I reinstalled the extension and it still seems to be happening. Top-level posts are the correct color, but code-level comments are still nearly invisible... anybody else still seeing it?

**Comment by leomotta121** [comment]
@poychang  I am using github default theme for while, once the new version is online could you please comment here? I am getting email notifications of this issue! Happy coding!

**Comment by tariq86** [comment]
This is still occurring for me with Firefox version 70.0b4 and extension version 1.0.20. It looks like the issue is coming from a `.timeline-comment ` rule in `discussion-timeline.scss`.

Manually adding the following rule fixes the issue for me:
```css
.timeline-comment {
  color: #d6d8da;
}
```

**Comment by poychang** [comment]
@tariq86 Thanks! I merge your PR and update to v1.0.21
But unfortunately, Google reviewing the extension being slow then ever. v1.0.20 still stuck right now. I have to publish v1.0.21 after they done.  It will be  wait for a while...

**Comment by madprops** [comment]
Still happening on the Firefox update that was released 15 hours ago. (I removed and reinstalled to be sure).

http://i.imgur.com/YsH7P81.png

**Comment by tariq86** [comment]
> Still happening on the Firefox update that was released 15 hours ago. (I removed and reinstalled to be sure).
> 
> http://i.imgur.com/YsH7P81.png

Can you double-check what version of the extension you have installed? I'm on 1.0.21 now and the fix is working for me.

**Comment by EvaFro** [comment]
I just updated to 1.0.21 and it works great! Thanks for fixing this!

**Comment by 333fred** [comment]
Thanks poychang, 1.0.21 is working great on FF.

**Comment by madprops** [comment]
Yeah it's working. Thanks.

**Comment by poychang** [comment]
Thank you your patients and support. I finally can close this issue 😅
