### ISSUE TITLE
Invert the activity colors

### ISSUE THREAD

**Issue by JohannesKlauss** [poychang/github-dark-theme#57]
Currently only the least activity color changes to a darker one but the more activity indicators are still the same. So the scale starts at dark, jumps to very light in the next step and goes to dark again. This looks a bit confusing, so I suggest to invert the scale, so it goes from dark (least) to light (most).
<img width="151" alt="Bildschirmfoto 2019-09-13 um 12 41 59" src="https://user-images.githubusercontent.com/6214415/64857192-289c2800-d624-11e9-85d4-935f2bfc660a.png">

**Comment by poychang** [comment]
I think changing the color of contributions table will make too much confuse. I'll change the color back to default. If anyone feel color of less contributions is too light, try to contribute more 👨🏻‍💻👩🏻‍💻
