### ISSUE TITLE
Issue label text is very hard to read

### ISSUE THREAD

**Issue by madrev** [poychang/github-dark-theme#61]
![image](https://user-images.githubusercontent.com/11656572/65184209-e6a32580-da19-11e9-8191-52c96304351b.png)

Since the color of the label does not change in dark mode, I think it makes sense for the color of the text overlaying it to stay the same.

**Comment by tariq86** [comment]
What browser and extension version are you using? This was fixed in PR #54, and looks fine for me in Firefox v70, extension v1.0.25

**Comment by poychang** [comment]
@madrev can you share more version information?

**Comment by madrev** [comment]
Sure! Sorry, should have thought to do that before.

Chrome on Mac:
Version 76.0.3809.132 (Official Build) (64-bit)

Extension version 1.0.25

**Comment by Engineerq** [comment]
Same
![image](https://user-images.githubusercontent.com/48583049/65815653-8bd0b180-e203-11e9-8a51-369151d037ec.png)
1.0.25
Chrome v77.0.3865.90

**Comment by poychang** [comment]
@madrev @Engineerq is that public repo? Can I check it out? It is hard to figure it out with no example. If it is public repo, please provide the link, thanks!

**Comment by tariq86** [comment]
@Engineerq that looks like a screenshot of the example screenshot from @madrev’s post...we are not changing text color in screenshots. Are you seeing the same issue on other labels?

**Comment by Engineerq** [comment]
My bad, I thought I had the same problem. It works fine except when I select a label in an issue.
![image](https://user-images.githubusercontent.com/48583049/65838652-52d53180-e316-11e9-81bb-61670c5c3f75.png)

**Comment by Engineerq** [comment]
@tariq86 this problem exists in the project cards labels.
![image](https://user-images.githubusercontent.com/48583049/65867514-a0d64d80-e387-11e9-8442-54742eab9a0a.png)

**Comment by poychang** [comment]
Can not repeat this issue. Close this issue. If anyone has the same problem, please open new issue and list the repeat step.
