### ISSUE TITLE
Images in Markdown should have transparent background

### ISSUE THREAD

**Issue by vinyldarkscratch** [poychang/github-dark-theme#62]
Something I noticed is that images have a background that's a little darker than the background for Markdown blocks.  I feel, however, that if an image has transparency, it should be kept transparent to keep the same appearance as in regular GitHub pages.  I'm proposing that `.markdown-img` have a background color of either `transparent` or even `rgb(36, 41, 46)`.

Light Theme:
<img width="268" alt="Screen Shot 2019-10-04 at 21 20 53" src="https://user-images.githubusercontent.com/5179191/66249764-268e2c00-e6ed-11e9-8571-45dc87be5a71.png">

Dark Theme (Current):
<img width="338" alt="Screen Shot 2019-10-04 at 21 21 05" src="https://user-images.githubusercontent.com/5179191/66249768-2c840d00-e6ed-11e9-82e5-b82aa51022c7.png">

Dark Theme (After Proposed Changes):
<img width="282" alt="Screen Shot 2019-10-04 at 21 21 29" src="https://user-images.githubusercontent.com/5179191/66249773-3574de80-e6ed-11e9-9ced-c0a68d11c32c.png">

**Comment by poychang** [comment]
I vote transparent. Thanks @vinyldarkscratch notice this!
