### ISSUE TITLE
stackoverflow.com does not work

### ISSUE THREAD

**Issue by kopax** [poychang/github-dark-theme#73]
Hi, I've just tested your plugin and I found it awesome so I can protect my eyes thanks.

Another website developer use a lot is stackoverflow, but it doesn't work well yet:

![image](https://user-images.githubusercontent.com/1866564/68063499-df0db680-fd11-11e9-913a-be57b5b7b236.png)

Any idea how to fix this?

Source : https://stackoverflow.com/

**Comment by poychang** [comment]
Glad hear that. But this extension only focus on GitHub, not general website. I visit stackoverflow a lot and waiting someone who can create another eye protect theme too.

**Comment by kopax** [comment]
Oh sorry, because it's possible to add other domain, I tought it was supported. Because developer use stackoverflow  a lot. Too bad I wish I could see it dark. I love this dark theme thanks for sharing it.

**Comment by kopax** [comment]
@poychang what about supporting gitlab ? It's almost that but we can't see for example the text of an issue. But you can see reply to this issue. Is it hard to add more domain so I can support gitlab and stackoverflow ?
