### ISSUE TITLE
issue progress bar seems reversed

### ISSUE THREAD

**Issue by chancesmith** [poychang/github-dark-theme#76]
the progress bar looks like it's inverted
![Screen Shot 2019-11-15 at 1 51 42 PM](https://user-images.githubusercontent.com/4466585/68971484-3babaf80-07af-11ea-9502-f4cd46433773.png)

an incomplete list looks complete
![Screen Shot 2019-11-15 at 1 53 54 PM](https://user-images.githubusercontent.com/4466585/68971570-685fc700-07af-11ea-9d13-433805ab70ce.png)

**Comment by lucacataldo** [comment]
Hey, I've noticed this as well. I'd like to work on it.
