### ISSUE TITLE
Italic and bold in Markdown file are not readable

### ISSUE THREAD

**Issue by gsebil08** [poychang/github-dark-theme#81]
![image](https://user-images.githubusercontent.com/45454460/69355695-867f6880-0c82-11ea-9144-294c5ef72d3f.png)
\*locale* is written after `by`
![image](https://user-images.githubusercontent.com/45454460/69356521-e3c7e980-0c83-11ea-893b-40785eeb0d9d.png)
Not more readable on deleted line...
Neither on added line...

**Comment by poychang** [comment]
It will be fix in next version. Thanks for your report.
