### ISSUE TITLE
Label text incorrectly inverted in project board view

### ISSUE THREAD

**Issue by sambostock** [poychang/github-dark-theme#82]
Labels with a light background use dark text. That dark text appears to be inverted by the extension, which makes it hard to read.

Normal|Dark Theme
-|-
![image](https://user-images.githubusercontent.com/8219340/69366880-26c69480-0c65-11ea-8092-efd6b88193e0.png)|![image](https://user-images.githubusercontent.com/8219340/69366248-f6322b00-0c63-11ea-9807-215ca5dd6c4d.png)

Text foreground color in labels should not be inverted, as the label background isn't affected by dark mode.

## Reproduction Steps

- Use Chrome
- Create a label with a light colour (e.g. `#c5def5`)
- Apply the label to an issue
- Add that issue to a project board
- View project board

----

Relates to #61

**Comment by poychang** [comment]
It will be fix in v1.0.30.  Thanks for your report.
